"""
PDF Generator Module
Generate professional PDF reports from case data
"""

from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


class PDFReportGenerator:
    """Generate PDF reports for forensic investigations."""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#1e1e2e')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#313244')
        ))
        
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceBefore=6,
            spaceAfter=6,
        ))
        
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            alignment=TA_CENTER,
            textColor=colors.grey
        ))
    
    def generate_report(
        self,
        output_path: str,
        case_info: Dict[str, Any],
        evidence_list: List[Dict[str, Any]],
        stats: Dict[str, Any],
        activity_log: List[Dict[str, Any]] = None
    ):
        """
        Generate a full investigation report.
        
        Args:
            output_path: Path for the output PDF file
            case_info: Dictionary with case details
            evidence_list: List of evidence dictionaries
            stats: Statistics dictionary
            activity_log: Optional list of activity log entries
        """
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        # Title page
        story.extend(self._create_title_page(case_info))
        story.append(PageBreak())
        
        # Executive summary
        story.extend(self._create_summary_section(case_info, stats))
        
        # Evidence table
        story.extend(self._create_evidence_section(evidence_list))
        
        # Statistics
        story.extend(self._create_statistics_section(stats))
        
        # Activity log
        if activity_log:
            story.extend(self._create_activity_section(activity_log))
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            f"Generated by Evidentia on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            self.styles['Footer']
        ))
        
        # Build PDF
        doc.build(story)
    
    def _create_title_page(self, case_info: Dict[str, Any]) -> list:
        """Create the title page elements."""
        elements = []
        
        elements.append(Spacer(1, 2 * inch))
        
        elements.append(Paragraph(
            "INVESTIGATION REPORT",
            self.styles['ReportTitle']
        ))
        
        elements.append(Spacer(1, 0.5 * inch))
        
        elements.append(Paragraph(
            case_info.get('name', 'Untitled Case'),
            ParagraphStyle(
                'CaseTitle',
                parent=self.styles['Heading1'],
                fontSize=18,
                alignment=TA_CENTER
            )
        ))
        
        elements.append(Spacer(1, 0.3 * inch))
        
        # Case details
        case_type = case_info.get('case_type', 'General Investigation')
        status = case_info.get('status', 'Active')
        created = case_info.get('created_at', datetime.now())
        
        if isinstance(created, str):
            created_str = created
        else:
            created_str = created.strftime('%Y-%m-%d')
        
        details = [
            f"Case Type: {case_type}",
            f"Status: {status}",
            f"Created: {created_str}",
            f"Report Date: {datetime.now().strftime('%Y-%m-%d')}"
        ]
        
        for detail in details:
            elements.append(Paragraph(
                detail,
                ParagraphStyle(
                    'Detail',
                    parent=self.styles['Normal'],
                    alignment=TA_CENTER,
                    spaceBefore=5
                )
            ))
        
        elements.append(Spacer(1, inch))
        
        # Confidentiality notice
        elements.append(Paragraph(
            "CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY",
            ParagraphStyle(
                'Confidential',
                parent=self.styles['Normal'],
                fontSize=10,
                alignment=TA_CENTER,
                textColor=colors.red
            )
        ))
        
        return elements
    
    def _create_summary_section(self, case_info: Dict[str, Any], stats: Dict[str, Any]) -> list:
        """Create the executive summary section."""
        elements = []
        
        elements.append(Paragraph("Executive Summary", self.styles['SectionHeader']))
        
        description = case_info.get('description', 'No description provided.')
        elements.append(Paragraph(description, self.styles['BodyText']))
        
        elements.append(Spacer(1, 15))
        
        # Quick stats table
        total = stats.get('total_evidence', 0)
        status_breakdown = stats.get('status_breakdown', {})
        
        data = [
            ['Metric', 'Count'],
            ['Total Evidence Files', str(total)],
            ['Analyzed', str(status_breakdown.get('Analyzed', 0))],
            ['Pending', str(status_breakdown.get('Pending', 0))],
            ['Flagged', str(status_breakdown.get('Flagged', 0))],
        ]
        
        table = Table(data, colWidths=[3*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#313244')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f5f5f5')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
        ]))
        
        elements.append(table)
        
        return elements
    
    def _create_evidence_section(self, evidence_list: List[Dict[str, Any]]) -> list:
        """Create the evidence listing section."""
        elements = []
        
        elements.append(Spacer(1, 20))
        elements.append(Paragraph("Evidence Inventory", self.styles['SectionHeader']))
        
        if not evidence_list:
            elements.append(Paragraph("No evidence files in this case.", self.styles['BodyText']))
            return elements
        
        # Table header
        data = [['ID', 'File Name', 'Type', 'Modified Date', 'Status', 'Risk']]
        
        # Add evidence rows
        for evidence in evidence_list[:50]:  # Limit to 50 for PDF size
            modified = evidence.get('modified_time', '')
            if isinstance(modified, datetime):
                modified = modified.strftime('%Y-%m-%d')
            
            row = [
                str(evidence.get('id', '')),
                evidence.get('file_name', '')[:30],  # Truncate long names
                evidence.get('file_extension', '').upper().replace('.', ''),
                str(modified)[:10],
                evidence.get('status', 'Pending'),
                evidence.get('risk_level', 'Low'),
            ]
            data.append(row)
        
        table = Table(data, colWidths=[0.5*inch, 2.2*inch, 0.6*inch, 1*inch, 0.8*inch, 0.6*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#313244')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')]),
        ]))
        
        elements.append(table)
        
        if len(evidence_list) > 50:
            elements.append(Paragraph(
                f"Note: Showing 50 of {len(evidence_list)} evidence files.",
                self.styles['Footer']
            ))
        
        return elements
    
    def _create_statistics_section(self, stats: Dict[str, Any]) -> list:
        """Create the statistics section."""
        elements = []
        
        elements.append(Spacer(1, 20))
        elements.append(Paragraph("Risk Analysis", self.styles['SectionHeader']))
        
        risk_breakdown = stats.get('risk_breakdown', {})
        
        data = [
            ['Risk Level', 'Count', 'Percentage'],
        ]
        
        total = sum(risk_breakdown.values()) if risk_breakdown else 0
        
        for risk in ['Low', 'Medium', 'High']:
            count = risk_breakdown.get(risk, 0)
            pct = f"{(count / total * 100):.1f}%" if total > 0 else "0%"
            data.append([risk, str(count), pct])
        
        table = Table(data, colWidths=[1.5*inch, 1*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#313244')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (0, 1), colors.HexColor('#a6e3a1')),  # Low - green
            ('BACKGROUND', (0, 2), (0, 2), colors.HexColor('#f9e2af')),  # Medium - yellow
            ('BACKGROUND', (0, 3), (0, 3), colors.HexColor('#f38ba8')),  # High - red
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
        ]))
        
        elements.append(table)
        
        return elements
    
    def _create_activity_section(self, activity_log: List[Dict[str, Any]]) -> list:
        """Create the activity log section."""
        elements = []
        
        elements.append(Spacer(1, 20))
        elements.append(Paragraph("Activity Log", self.styles['SectionHeader']))
        
        if not activity_log:
            elements.append(Paragraph("No activity recorded.", self.styles['BodyText']))
            return elements
        
        data = [['Timestamp', 'Action', 'Details']]
        
        for entry in activity_log[-20:]:  # Last 20 entries
            timestamp = entry.get('timestamp', '')
            if isinstance(timestamp, datetime):
                timestamp = timestamp.strftime('%Y-%m-%d %H:%M')
            
            row = [
                str(timestamp),
                entry.get('action', ''),
                entry.get('details', '')[:40],
            ]
            data.append(row)
        
        table = Table(data, colWidths=[1.3*inch, 1.5*inch, 2.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#313244')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
        ]))
        
        elements.append(table)
        
        return elements
